platform :ios, "8.0"
use_frameworks!

target "SwiftProjiect" do

pod 'SVProgressHUD'
pod 'FDFullscreenPopGesture', '1.1'
pod 'Alamofire', '4.3.0'
pod 'SnapKit', '~> 3.1.2'
pod 'Kingfisher', '~>3.3.4'
pod 'SwiftyJSON', '~> 3.1.4'
pod 'MJRefresh', '3.1.12'

end
